baseurl: '/'
permalink: pretty
title: 'Python Coaching'

logo:
  mobile: "images/logo/logo3.png"
  mobile_height: "128px"
  mobile_width: "128px"
  desktop: "images/logo/logo.svg"
  desktop_height: "128px"
  desktop_width: "128px"

home: 
  limit_services: 12  

collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true
  pymodule:
    output: true
    sort_by: weight
    permalink: /python-course/:name

defaults:
  - scope:
      path: ""
      type: "pyModule"
    values:
      layout: "pymodule"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
